# include the general include file which contains the functions
source $srcdir/lib/include.tcl
# use the backends include file containing several 
# procedures special for algorithmic backends
source $srcdir/lib/backends.tcl


#cd into the test dir such that output files are placed here.
if { [file exists $binpaths(out) ] != 1 } {
    file mkdir $binpaths(out)
}
cd $binpaths(out)

puts "\n----------------------------------------------"
puts   "TESTING: Algorithmic backends for Mapa language"
puts   "----------------------------------------------\n"

# the number of threads to use in multithreaded backends
set num_threads 5

# Language Mapa-frontends:
# -------------------


set langs [dict create]
dict set langs mapa model "polling.mapa" 
dict set langs opaal options mc "--threads=$num_threads -v"
dict set langs mapa exp_output "27659 states 47130 transitions"
set alg_be [ find_alg_backends "{dist}" ]
run_test_for_alg_backends $alg_be $langs $backends

# different output for symbolic tool:
dict set langs mapa exp_output "state space has 27659"
set alg_be [ find_alg_backends "{sym}" ]
run_test_for_alg_backends $alg_be $langs $backends


cd ".."
